INSERT INTO BankSample (
	[BankID]
    ,[UniqueNum]
    ,[Name]
    ,[Address1]
    ,[Address2]
    ,[City]
    ,[State]
    ,[Zip]
    ,[Deposit]
    ,[Lat]
    ,[Lng]
    ,[ClosestStationID]
    ,[ClosestPSDistance]
    ,[MeanPSDistance]
    ,[PSCount]
    ,[Take]
    ,[PDistance]
    ,Officers1000
    ,[FFLCount]
	,[AvgRating]
	 )
SELECT TOP 10 PERCENT 
	[BankID]
    ,[UniqueNum]
    ,[Name]
    ,[Address1]
    ,[Address2]
    ,[City]
    ,[State]
    ,[Zip]
    ,[Deposit]
    ,[Lat]
    ,[Lng]
    ,[ClosestStationID]
    ,[ClosestPSDistance]
    ,[MeanPSDistance]
    ,[PSCount]
    ,[Take]
    ,[PDistance]
    ,Officers1000
    ,[FFLCount]
	,[AvgRating]
FROM Bank
ORDER BY rand(checksum(*))

